### ISSUE TITLE
As a user, I can search for ingredients and get a list of recipes that contain those ingredients.

### ISSUE THREAD

**Issue by kmewrd** [lswatson16/stretch-tech#1]
- [x] Make controlled form w/ text inputs for user to enter search terms (ingredients).
- [x] Find some way for user to enter multiple ingredients (comma separated list or separate fields?).
- [x] Will need a container that holds recipe cards (image, title, and 'See Details' button).
- [x] Recipe cards should be their own component.
- [x] Should see a message if no recipes match the search criteria. (E.g. Sorry, there are no recipes that contain [ingredients here].)

**Comment by lwatz** [comment]
Documentation for [React Loader Spinner](https://github.com/mhnpd/react-loader-spinner)
