### ISSUE TITLE
As a user, I can filter search results based on health/diet labels

### ISSUE THREAD

**Issue by kmewrd** [lswatson16/stretch-tech#3]
- [x] In addition to a search form, we could create an additional component called Filter that has filtering criteria. There are both healthLabels and dietLabels on the returned data from Edamam, so there could be two <select> elements that overlap.
- [ ] Results should immediately update with new filtering criteria.

**Comment by lwatz** [comment]
We hooked up the filtering by health labels. The labels are displayed in a dropdown menu.
